### ISSUE TITLE
Practica5-DiegoAlexisCarlosCruz 

### ISSUE THREAD

**Issue by g00gle2401** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-g00gle2401#2]
[Practica5-DiegoAlexisCarlosCruz.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-g00gle2401/files/8346544/Practica5-DiegoAlexisCarlosCruz.pdf)

**Comment by Gregorio012** [comment]
Calificación 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
